Cmdr/Shared/Dispatcher.lua, Cmdr/Shared/Registry.lua
#29 
Add a third parameter to `Registry:AddHook` that takes an optional integer indicating the priority of the hook. The lower the value, the higher the priority. The default is 0.
=> Add hook priorities

Cmdr/BuiltInCommands/clear.lua, Cmdr/CmdrClient/CmdrInterface/Window.lua
Closes #44 
There is one limitation to this implementation, in that when you run the command you are left with a "Window cleared." text at the top of the GUI.
To get around this, a way to actually return nothing from a command may be necessary.
=> Add a client-side clear command

Cmdr/Shared/Registry.lua
This implementation throws errors on the client if a registered command has both a `Data` and `Run` section declared.
It also errors if a registered type's name is `nil`, if it isn't a string, if it contains anything other than letters, or doesn't start with a lowercase letter.
=> Add Registry Validation

Cmdr/Initialize.lua
This should help prevent issues when there's a non-RoStrap object
named "Resources" in ReplicatedStorage.
=> Add additional check for RoStrap installation

.luacheckrc, Cmdr/CmdrClient/CmdrInterface/Window.lua
Fixes multi-line text being clipped through everything in the console due to incorrect Y offset size in the textlabel.
=> Fix multi-line text clipping.

docs/api/Registry.md
RegisterHook's first parameter was called 'hookName' but is now called '"BeforeRun" | "AfterRun"' to be more clear to new users.
=> Update docs/registry (RegisterHook) #94

Cmdr/CreateGui.lua
Fixes Cmdr input from being automatically captured and shown in the localization portal.
=> Disable AutoLocalize for Cmdr ScreenGui

CHANGELOG.md, Cmdr/BuiltInTypes/Player.lua
The purpose of this pull request is to add the ability to select random players with the `player` and `players` datatype.
Innovation Security (managed by non-developers) runs security trainings for the group and performs events. Some of these events rely on picking random players (between 1 and n), such as for snipers to stop everyone else from reaching the end of a map. The current syntax used as part of the older admin system (Nexus Admin) uses `random` as the selector, such as `:bring random,random,random` to bring 3 random players.
The change requested involves adding both ~`random` and~ `?` to the `player` type as selectors for selecting random players, as well as being able to select a specific amount of random players using ~`random[n]` and `?[n]`~ `?n` (as mentioned in …
=> Add Random Player Selector

CHANGELOG.md, Cmdr/CreateGui.lua
See #124 
I took the liberty to remove the auto-generated notice. Judging by the files currently in version control I assume that was some legacy method of creating this file.
=> Fixed so TextBox is not selectable using controller #124

CHANGELOG.md, Cmdr/Shared/Registry.lua
The purpose of this pull request is to fix `AutoExec` commands being executed multiple times if a command is registered at a later frame, such as creating an alias.
The change requested involves adding a clear for the `AutoExecBuffer` in the `FlushAutoExecBuffer` function. This clears the commands to execute and prevents them from being rerun when called.
=> Clear AutoExecBuffer on FlushAutoExecBuffer

Cmdr/Shared/Util.lua
Util.SplitString has an initialization line where 4 variables are assigned to an expression with two values. This causes a linter warning in Script Analysis in Studio - "Assigning 2 values to 4 variables initializes extra variables with nil; add 'nil' to value list to silence".
=> Fix uninitialized variable Script Analysis warning

Cmdr/Shared/Command.lua, docs/api/CommandContext.md
I made a BeforeRun and AfterRun hook on client, it sends the info to remote function(to validate things on server) then returns the response, the thing is while client commands get validated and logged 1 times on the server, Server commands get 2 times because both the client sends info and server has the hooks.
This will allow me(and others) to check if the command is client sided then sends the info so it doesnt get double validated and logged.
=> Add HasImplementation function to CommandContext

Cmdr/BuiltInTypes/Duration.lua
This commit catches whitespace added by pressing enter (if any) after the ending unit (second/minute/hour/day). Without the added %s?, endingUnit would be nil.
=> Update endingUnit String Pattern

Cmdr/Shared/Registry.lua
t[#t + 1] = x has been superseded by table.insert(t, x).
=> Change how tables are indexed

Cmdr/BuiltInCommands/help.lua, Cmdr/Shared/Registry.lua
Categorize the commands displayed by the groups pulled from each command definition for easier readability.
=> Organize the help command

default.project.json, test-place.project.json, wally.toml
(This is a trial of a batch of PRs that I'm sending around to a bunch of repositories. I've talked about this with Eryn, let's iron out the wrinkles here before I go and open a bunch of other PRs!)
Hello!
This PR adds a manifest file for [Wally][wally], a new package manager created for Roblox by Uplift Games.
This change enables users to install this package by adding a line to their `wally.toml` manifest:
```toml
[package]
name = "lucien/my-game"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
[dependencies]
Cmdr = "evaera/cmdr@1.8.4"
```
We're currently running a soft rollout for wally where Uplift Games publishes packages on behalf of library authors. In the near future, library authors will be able to publish packages themselves.
Wally works …
=> Add Wally manifest

Cmdr/Shared/Util.lua
The pattern "^%s*(.-)%s*$" doesn't do well for strings that have a large number of whitespace characters between non-whitespace characters.
Inspired by: https://stackstatus.net/post/147710624694/outage-postmortem-july-20-2016
Test bench: https://gist.github.com/Validark/c86a3e92dde76d26e6893d796dfea89a
=> Prevent quadratic backtracking in TrimString function

CHANGELOG.md, Cmdr/Shared/Argument.lua
In the `GetDefaultAutocomplete` method, only 1 return value from `Argument:TransformSegment` is accounted. So when the `Transform` function returns more than 1 value,  sometimes only the first value is passed to `Autocomplete`, `Validate` and `Parse`, and the rest are disregarded. 
This is currently happening with a custom type I've created in which the transform method returns more than 1 value, the  executor and the results from `Util.MakeFuzzyFinder(Players:GetPlayers())` which are later used in my `ValidateOnce`  method. However, errors occur because `ValidateOnce` is only passed the executor, and not the second value i.e `findPlayer(text)`.  This pull request fixes this issue easily with just a very small edit. 
**This issue happens when I try to use value operators like ** and . for …
=> Fix incorrect number of arguments passed to `AutoComplete`, `Validate` and `Parse` on using value operators like `**`

Cmdr/CmdrClient/CmdrInterface/Window.lua, Cmdr/CreateGui.lua
replaced "Line" TextBox with a TextLabel (wasn't being treated as a TextBox)
uses a UIListLayout instead of relying on code to position entry field (a roblox update somehow broke the positioning)
=> Entry Line Behavior

Cmdr/CmdrClient/CmdrInterface/Window.lua, Cmdr/CreateGui.lua
richtext enabled on output messages and changed "Line" to a textlabel since it wasn't being treated as a textbox
couldn't enable richtext on the entry line due to the way ui text rendering behaves
Closes #157
=> Output RichText

Cmdr/BuiltInCommands/Admin/gotoPlaceServer.lua
TeleportPartyAsync can only teleport to a place in the same universe. I replaced it with the new TeleportAsync, which can teleport to places in a different universe.
=> Replace TeleportPartyAsync with TeleportAsync

Cmdr/Shared/Registry.lua
`Registry:RegisterType` has a quick type check on its first line wherein the `name` parameter is verified to be non-nil and a string. However, the bool expression checking this has a typo...
```lua
not typeof(name) == "string"
```
...which is equivalent to...
```lua
(not typeof(name)) == "string"
```
...which does not properly perform this check. It always evaluates to false. The expression should be...
```lua
not (typeof(name) == "string") -- or more simply:
typeof(name) ~= "string"
```
The Roblox's Script Analysis window reports this as a [ComparisonPrecedence](https://luau-lang.org/lint#comparisonprecedence-28) lint. This PR corrects the expression to use `~=`, fixing the logic issue and the lint.
=> Typo in Registry:RegisterType

Cmdr/Initialize.lua, docs/guide/Setup.md
Currently, CmdrClient will parent itself in `ReplicatedStorage.Resources.Libraries` if there is an instance at that path.
This behaviour was originally implemented to support the RoStrap, which allow CmdrClient to be required via its own loader.
However, this behaviour is undocumented and given the generic names used, confusing. Developers rightly expect CmdrClient to appear under `ReplicatedStorage`.
Additionally, RoStrap is out of date and seems to no-longer be used in the community and [Cmdr with RoStrap appears to not even work](https://github.com/evaera/Cmdr/commit/0a2f29ab44a399d95f29b0558cd5220e8750863d).
This pull request:
- removes this behaviour
- removes the (commented out) references to RoStrap in the docs' Setup guide
=> Remove RoStrap support

docs/guide/Setup.md
I didn't know that it was available on Wally, so it'd be helpful to mention for people already using it for their projects. Included under `server-dependencies` to emphasize it being installed under a server directory like ServerStorage
=> Mention Wally as a setup option in docs

Cmdr/CmdrClient/CmdrInterface/Window.lua, Cmdr/CreateGui.lua
manual sizing created empty gaps on lengthy richtext strings
=> Automatic Line Sizing

Cmdr/BuiltInCommands/Utility/runLines.lua, Cmdr/Shared/Util.lua
Redo of #177
While working with Innovation Security, we discovered a couple of things with respect to `run-lines` when using `init-edit` and `init-run`:
- By default, it doesn't appear to work at all since it uses `Dispatcher:Run(...)`, which only works on the client, but is called by the server.
- `run-lines` does not work with client commands, like `alias`.
- `run-lines` throws an error if the input text contains a percent character anywhere.
This pull request attempts to address those problems by making `run-lines` run on the client instead of the server, and escape percent characters before being used with `gsub`.
=> Improve run-lines Functionality

Cmdr/CmdrClient/CmdrInterface/Window.lua
There is currently an issue with the new TextChatService where if you're using it instead of the old Lua chat, the chat window will show over the Cmdr bar since it's now living in CoreGui, making it impossible to read. This is the cleanest fix I can think of at the moment; I simply to toggle Enabled on the input bar and chat tray in Window.SetVisible. I have made this fork already in my own game and it seems to work well.
=> Fix command bar being obscured by TextChatService

CHANGELOG.md, Cmdr/BuiltInTypes/Player.lua, Cmdr/BuiltInTypes/PlayerId.lua, Cmdr/CmdrClient/CmdrInterface/AutoComplete.lua, Cmdr/Shared/Argument.lua, Cmdr/Shared/Registry.lua, Cmdr/Shared/Util.lua, docs/api/Registry.md
Allows you to use "me", "all", "others" and "random" as an argument shorthand for Player and PlayerId types. 
Doesn't prevent you from using the default shorthands.
=> Add ArgumentOperatorAliases to Player types

Cmdr/CmdrClient/CmdrInterface/Window.lua, Cmdr/CmdrClient/init.lua
This makes the canvas auto scroll to the bottom on any text input.
On by default, call `Cmdr:CanvasAutoScrollToBottom()` with param `isEnabled` to set the behaviour
=> Implement auto scroll to the bottom of the canvas on user text input

Cmdr/CmdrClient/CmdrInterface/Window.lua
The UIListLayout.AbsoluteContentSize property takes a moment to update after the new line is parented to the ScrollingGui. I have delayed the update to ensure proper sizing of the GUI.
=> Delay Updating the Window Height

Cmdr/CmdrClient/CmdrInterface/AutoComplete.lua, Cmdr/Shared/Util.lua
I've found that it's frustrating not being able to have autocomplete when I type something that isn't the direct beginning of a final result. This is especially true when it comes to custom types and usernames. Being able to type `username` instead of `123xxx_username` is convenient/better/faster.
I've calculated the two strings required to display the autocomplete text in this PR like so:
```lua
"       user    " -- Typed.Text
"123xxx_    name" -- Suggest.Text
````
Combined it gives the same result as previously. It doesn't break previous usage.
=> Improve FuzzyFind/AutoComplete

Cmdr/CmdrClient/CmdrInterface/AutoComplete.lua, Cmdr/CreateGui.lua
=> Fix AutoComplete Menu Max Size

Cmdr/BuiltInCommands/Utility/var.lua, Cmdr/BuiltInCommands/Utility/varSet.lua
I don't really know much about lua and Cmdr, so I consider this a very good solution. Before, users could use init-edit-global to force administrators or other users to run commands. Once someone with permission to run the init command joined, it would be run, regardless if the original user had permissions to run it.
=> init-edit and init-edit-global permission fix

Cmdr/BuiltInCommands/Admin/gotoPlace.lua, Cmdr/BuiltInCommands/Utility/pick.lua, Cmdr/BuiltInTypes/PlayerId.lua
- Type `playerId` will now piggy back off of the `positiveInteger` type when utilising the `#` prefix;
- Command `pick` uses the `positiveInteger` type as arrays/dictionaries created from the `:split()` string function do not have any indexes lower than 0;
- Command `goToPlace` uses the `positiveInteger`
=> Utilising positiveInteger in BuiltInTypes and BuiltInCommands

Cmdr/CmdrClient/CmdrInterface/AutoComplete.lua
In Nexus Admin (which uses Cmdr as a base), players are handled *very* differently to handle aliases and sets. When it autocompletes, it will return a list of players when an alias is typed in. When the original string is not part of what is returned by the autocomplete outside of aliases, say your autocomplete had an alias to turn `"creator"` into `"TheNexusAvenger"` for whatever reason, it causes an error in the autocomplete. This adds a check for when the `start` and `stop` variables become `nil` and adds default values when this happens.
Nexus Admin 2.7.2 uses this change in live games already.
Example meant to be run in a `LocalScript` that shows the issue. It creates a command `test` that will autocomplete with the string given unless it is exactly `preset`. Using `test preset` will …
=> Fix AutoComplete Error When Type Returns Completely Different String

Cmdr/CmdrClient/DefaultEventHandlers.lua
The announcement command now works with TextChatService as well as the LegacyChatService.
=> Announcement Command -> TextChatService

Cmdr/BuiltInCommands/help.lua
=> Fix `help [command]` Broken by Inline Arguments

Cmdr/Shared/Command.lua, Cmdr/Shared/Dispatcher.lua, Cmdr/Shared/Registry.lua
Closes #86 
- Guard methods are checked before hooks.
- When a guard method is called, the first parameter is the command context.
- The dispatcher also supports sending additional parameters as varargs (similar to hooks), though this is not used in standard command execution.
- If the guard method returns a non-nil value, the command will be interrupted and the value printed to the window.
**Example usage:**
```
return {
-- <insert command object here with name, aliases, description, etc.>
Guards = {
function(self)
if math.random(1,3) == 2 then
return "You are unlucky!"
end
end;
function(self)
return if self.Executor.UserId ~= 92658764 then "You are not allowed to do this!" else nil
end;
};
}
```
=> Add command-specific guard methods

SECURITY.md
This pull request introduces a new security policy. A security policy is necessary because:
- it shows to our users that we take security seriously and value reports
- it makes it clear to reporters what we expect of them, how we'll handle their reports, and how they can get in touch
- it makes clear to our users that they shouldn't expect us to provide security fixes or support for older versions of Cmdr
- it explains to researchers and our users what we do not consider to be security issues
In the past few months, we've had at least two incidents where a user has attempted to report a security vulnerability by making a pull request or other public report (e.g. on an online forum or via our support channels). This policy will help prevent incidents like that.
**Next steps**
We should …
=> Create and publish security policy

Cmdr/BuiltInCommands/Debug/version.lua, Cmdr/BuiltInCommands/Utility/echo.lua, Cmdr/BuiltInCommands/Utility/jsonArrayEncode.lua, Cmdr/BuiltInCommands/Utility/len.lua, Cmdr/BuiltInCommands/Utility/pick.lua, Cmdr/BuiltInCommands/Utility/rand.lua, Cmdr/BuiltInCommands/Utility/replace.lua, Cmdr/BuiltInCommands/Utility/resolve.lua, Cmdr/BuiltInCommands/Utility/run.lua, Cmdr/BuiltInCommands/Utility/runif.lua, Cmdr/Shared/Util.lua
`ClientRun` has been preferred to `Run` for some time now. While most built-in commands are now using `ClientRun`, some are still using the legacy `Run` definition.
It's important that our built-in commands are good examples and therefore shouldn't exhibit deprecated or unadvised behaviour. Accordingly, this pull request changes those remaining built-in commands to use the new `ClientRun` function.
=> Change built-in commands to use `ClientRun` over `Run`

Cmdr/Shared/Registry.lua
Adds a `container` argument to RegisterHooksIn. Had to manually add a `@param` so this may be a Moonwave limitation, as RegisterHooksIn is defined as RegisterTypesIn.
**Declarations**:
=> Add container argument to RegisterHooksIn

Cmdr/CmdrClient/CmdrInterface/Window.lua
Closes #336. Checks if PlaceName exists and is not an empty string. Replaces string concatenation with string interpolation.
**Declarations**:
=> Abridge entry when PlaceName is empty

Cmdr/BuiltInCommands/Admin/announceServer.lua
Roblox wants developers to [migrate to using TextChatService](https://devforum.roblox.com/t/integrate-textchatservicecanusersdirectchatasync-or-textchannelsetdirectchatrequester-api-to-comply-with-settings/3255672).
This pull changes `Chat:CanUsersChatAsync` to `TextChatService:CanUsersChatAsync`.
**Declarations**:
=> Migrate to TextChatService:CanUsersChatAsync

Cmdr/CmdrClient/CmdrInterface/Window.lua
Makes [channel tabs](https://devforum.roblox.com/t/channel-tabs-ui-gradient-now-available-in-textchatservice/3249560) hide with the rest of the chat when the Cmdr interface is visible
Old
New 
**Declarations**:
=> Support ChannelTabsConfiguration hiding
